[tox]
envlist = py311, py312, py313
isolated_build = True

[testenv]
deps =
    pytest
# PYTHONPATHにsrcを追加して、テストからmain.pyをインポート可能にします
setenv =
    PYTHONPATH = {toxinidir}/python/src
commands =
    # python/test ディレクトリ内のテストを実行
    pytest {posargs:python/test}